### ISSUE TITLE
CI no longer succeeds

### ISSUE THREAD

**Issue by rmatthes** [nmvdw/GrpdHITs#22]
The problem: one build in the CI is with legacy Coq 8.16, the other with "latest", which is now Coq 8.18, and the latter breaks with `Error: Case analysis on private inductive gquot`.

Compiling on my own Linux machine with Coq 8.17.1 works fine, so Coq 8.16 should be replaced by Coq 8.17.

I have no suggestion for the "latest" build.

**Comment by nmvdw** [comment]
Yes. They changed private inductive types in Coq 8.18, and I waited with fixing this issue until Coq 8.18 came out (the error did not come up in 8.17). I have time to fix this error in October.

**Comment by rmatthes** [comment]
Would it not be better to deactivate the CI with 8.18 for the time being? And at least go from 8.16 to 8.17 for the other build?

**Comment by nmvdw** [comment]
I am fine with temporary deactivation. I don't know how long I will need to solve it.

**Comment by benediktahrens** [comment]
How can we make sure we remember to activate the build again?

**Comment by nmvdw** [comment]
It is something that I should remember when I fix it.

**Comment by rmatthes** [comment]
I think if a pull request is being made to fix the problem, the open issues will not be forgotten to look at.
